### ISSUE TITLE
pick a domain!

### ISSUE THREAD

**Issue by yue4u** [saone19/saone#2]
Since @BeeVin 's work is so great. I think It'll be great to have a nice domain.

Here are some options I think that makes sense.

- `saone.dev`
- `saone.life`
- `saone.world`
- `saone.digital`
- `saone.design`

You can find other domains via vendors like namecheap and godaddy.

(actually `sa.one` is a valid domain but already owned by others)

**Comment by NikenN** [comment]
saone.world sounds cool tehe

**Comment by yue4u** [comment]
settle down to `saone.digital`! 🎉🎉
